reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  review_details: false
  auto_review:
    enabled: true
    drafts: false

  path_filters:
    - "functions/**"
    - "layers/common/src/**"
    - "scripts/**"
    - "tests/**"
    - "infrastructure/**"
    - "types/**"
    - "template.yaml"
    - "template.yml"
    - "package.json"
    - "samconfig.toml"
    - "tsconfig.json"
    - "jest.config.js"
    - "jest.integration.config.js"
    - "README.md"
    - "coderabbit.yaml"
    - ".github/workflows/**"
    - "!node_modules/**"
    - "!.aws-sam/**"
    - "!dist/**"
    - "!build/**"
    - "!coverage/**"
    - "!**/*.lock"
    - "!**/*.min.*"

chat:
  auto_reply: true