AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM TypeScript POC - API Gateway, Lambda, DynamoDB

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: !If [IsProd, "info", "debug"]

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Resources:
  # DynamoDB Table
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "aws-sam-poc-items-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # StreamSpecification:
      #   StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: aws-sam-poc

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "Accounts-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: account_id
          AttributeType: S
      KeySchema:
        - AttributeName: account_id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: aws-sam-poc

  FileUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "aws-sam-poc-file-upload-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AutoDeleteAfter7Days
            Status: Enabled
            ExpirationInDays: 7
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: aws-sam-poc

  # Lambda Layer - Shared code
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "aws-sam-poc-common-${Environment}"
      Description: Shared utilities and services
      ContentUri: layers/common/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Delete

  # API Gateway HTTP API
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "aws-sam-poc-api-${Environment}"
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300

  # Lambda: List items
  ListItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "aws-sam-poc-list-items-${Environment}"
      CodeUri: functions/list-items/
      Handler: src/handler.handler
      Description: List all items from DynamoDB
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        ListApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /items
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/handler.ts
        External:
          - "@aws-sdk/*"
          - "common"
          - "common/*"

  # Lambda: Get single item
  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "aws-sam-poc-get-item-${Environment}"
      CodeUri: functions/get-item/
      Handler: src/handler.handler
      Description: Get a single item by ID
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /items/{id}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/handler.ts
        External:
          - "@aws-sdk/*"
          - "common"
          - "common/*"

  # Lambda: Create item
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "aws-sam-poc-create-item-${Environment}"
      CodeUri: functions/create-item/
      Handler: src/handler.handler
      Description: Create a new item
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        CreateApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /items
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/handler.ts
        External:
          - "@aws-sdk/*"
          - "common"
          - "common/*"

  # Lambda: File upload
  FileUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "aws-sam-poc-file-upload-${Environment}"
      CodeUri: functions/file-upload/
      Handler: handler.handler
      Description: File upload function poc to S3 bucket
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref AccountsTable
          UPLOAD_BUCKET: !Ref FileUploadBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${FileUploadBucket}/*" # also can declare like  !Sub "${FileUploadBucket.Arn}/*"
      Events:
        FileUploadApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /file-upload
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handler.ts
        External:
          - "@aws-sdk/*"
          - "common"
          - "common/*"

Outputs:
  ApiUrl:
    Description: HTTP API Gateway endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  HttpApiId:
    Description: HTTP API ID
    Value: !Ref HttpApi
    Export:
      Name: !Sub "${AWS::StackName}-HttpApiId"
  ItemsTableName:
    Description: DynamoDB table name
    Value: !Ref ItemsTable
    Export:
      Name: !Sub "${AWS::StackName}-ItemsTableName"
  AccountsTableName:
    Description: DynamoDb table name for accounts
    Value: !Ref AccountsTable
    Export:
      Name: !Sub "${AWS::StackName}-AccountsTableName"
